#include <collisions/MAIN_TEST_SUITE__CORE_COLLISIONS.h>

INCLUDE_SUB_SUITES(CORE_COLLISIONS, 8,
INCLUDE_SUITE(hitbox_context),
INCLUDE_SUITE(hitbox_manager_instance),
INCLUDE_SUITE(collision_node),
INCLUDE_SUITE(collision_node_pool),
INCLUDE_SUITE(collision_resolver_aabb),
INCLUDE_SUITE(CORE_COLLISIONS_IMPLEMENTED),
INCLUDE_SUITE(CORE_COLLISIONS_CORE),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_COLLISIONS, END_TESTS);

