#include <inventory/implemented/MAIN_TEST_SUITE__CORE_INVENTORY_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_INVENTORY_IMPLEMENTED, 2,
INCLUDE_SUITE(item_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_INVENTORY_IMPLEMENTED, END_TESTS);

