#include <serialization/MAIN_TEST_SUITE__NO_GUI_SERIALIZATION.h>

INCLUDE_SUB_SUITES(NO_GUI_SERIALIZATION, 4,
INCLUDE_SUITE(no_gui_filesystem),
INCLUDE_SUITE(NO_GUI_SERIALIZATION_WIN64),
INCLUDE_SUITE(NO_GUI_SERIALIZATION_UNIX),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(NO_GUI_SERIALIZATION, END_TESTS);

