#include <collisions/core/aabb/MAIN_TEST_SUITE__CORE_COLLISIONS_CORE_AABB.h>

INCLUDE_SUB_SUITES(CORE_COLLISIONS_CORE_AABB, 3,
INCLUDE_SUITE(hitbox_aabb),
INCLUDE_SUITE(hitbox_aabb_manager),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_COLLISIONS_CORE_AABB, END_TESTS);

