#!/bin/sh
print_usage() {
    printf \
    "Usage: update_ui.sh [-b BACKEND]

            -b\ttarget backend\n"
}

BACKEND=''

while getopts 'b:f' flag; do
    case "$flag" in
        b) BACKEND="$OPTARG" ;;
        \?) ;;
        *) print_usage
            exit 1 ;;
    esac
done

if [ "$BACKEND" = "" ]; then
    print_usage
    printf "\n\tREQUIRED: -b\n"
    exit 1
fi

BACKEND=$(echo $BACKEND | tr '[:upper:]' '[:lower:]')

for file in $(find ./assets/ui/xml/$BACKEND/ -type f -iname "*.xml"); do
    BASENAME=$(basename $file)
    $LAVENDER_DIR/tools/lav_ui_builder -d "is_visualizing false" -b ${BACKEND} -f $BASENAME
done
