#include <game_action/implemented/entity/MAIN_TEST_SUITE__CORE_GAME_ACTION_IMPLEMENTED_ENTITY.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED_ENTITY, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED_ENTITY, END_TESTS);

