#include <serialization/unix/MAIN_TEST_SUITE__SDL_SERIALIZATION_UNIX.h>

INCLUDE_SUB_SUITES(SDL_SERIALIZATION_UNIX, 2,
INCLUDE_SUITE(unix_filesystem),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_SERIALIZATION_UNIX, END_TESTS);

