#include <rendering/implemented/MAIN_TEST_SUITE__CORE_RENDERING_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_RENDERING_IMPLEMENTED, 2,
INCLUDE_SUITE(aliased_texture_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_RENDERING_IMPLEMENTED, END_TESTS);

