#include <multiplayer/unix/MAIN_TEST_SUITE__SDL_MULTIPLAYER_UNIX.h>

INCLUDE_SUB_SUITES(SDL_MULTIPLAYER_UNIX, 3,
INCLUDE_SUITE(sdl_unix_tcp_context),
INCLUDE_SUITE(sdl_unix_tcp_socket),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_MULTIPLAYER_UNIX, END_TESTS);

