#include <debug/MAIN_TEST_SUITE__SDL_DEBUG.h>

INCLUDE_SUB_SUITES(SDL_DEBUG, 3,
INCLUDE_SUITE(sdl_debug),
INCLUDE_SUITE(SDL_DEBUG_OPENGL),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_DEBUG, END_TESTS);

