#include <ui/implemented/MAIN_TEST_SUITE__CORE_UI_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_UI_IMPLEMENTED, 2,
INCLUDE_SUITE(ui_window_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_UI_IMPLEMENTED, END_TESTS);

