#include <rendering/MAIN_TEST_SUITE__CORE_RENDERING.h>

INCLUDE_SUB_SUITES(CORE_RENDERING, 12,
INCLUDE_SUITE(sprite_manager),
INCLUDE_SUITE(animate_sprite),
INCLUDE_SUITE(graphics_window),
INCLUDE_SUITE(sprite),
INCLUDE_SUITE(aliased_texture),
INCLUDE_SUITE(aliased_texture_manager),
INCLUDE_SUITE(gfx_context),
INCLUDE_SUITE(texture),
INCLUDE_SUITE(graphics_window_manager),
INCLUDE_SUITE(CORE_RENDERING_IMPLEMENTED),
INCLUDE_SUITE(CORE_RENDERING_FONT),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_RENDERING, END_TESTS);

