#include <serialization/MAIN_TEST_SUITE__SDL_SERIALIZATION.h>

INCLUDE_SUB_SUITES(SDL_SERIALIZATION, 4,
INCLUDE_SUITE(sdl_filesystem),
INCLUDE_SUITE(SDL_SERIALIZATION_WIN64),
INCLUDE_SUITE(SDL_SERIALIZATION_UNIX),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_SERIALIZATION, END_TESTS);

