#include <rendering/opengl/glad/MAIN_TEST_SUITE__SDL_RENDERING_OPENGL_GLAD.h>

INCLUDE_SUB_SUITES(SDL_RENDERING_OPENGL_GLAD, 2,
INCLUDE_SUITE(glad),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_RENDERING_OPENGL_GLAD, END_TESTS);

