#include <multiplayer/win64/MAIN_TEST_SUITE__SDL_MULTIPLAYER_WIN64.h>

INCLUDE_SUB_SUITES(SDL_MULTIPLAYER_WIN64, 3,
INCLUDE_SUITE(sdl_win64_tcp_socket),
INCLUDE_SUITE(sdl_win64_tcp_context),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_MULTIPLAYER_WIN64, END_TESTS);

