#include <ui/handlers/MAIN_TEST_SUITE__CORE_UI_HANDLERS.h>

INCLUDE_SUB_SUITES(CORE_UI_HANDLERS, 2,
INCLUDE_SUITE(ui_gfx_window__closer__default),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_UI_HANDLERS, END_TESTS);

