#include <multiplayer/MAIN_TEST_SUITE__SDL_MULTIPLAYER.h>

INCLUDE_SUB_SUITES(SDL_MULTIPLAYER, 3,
INCLUDE_SUITE(sdl_tcp_context),
INCLUDE_SUITE(sdl_tcp_socket),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_MULTIPLAYER, END_TESTS);

