#include <multiplayer/MAIN_TEST_SUITE__SDL_MULTIPLAYER.h>

INCLUDE_SUB_SUITES(SDL_MULTIPLAYER, 5,
INCLUDE_SUITE(sdl_tcp_context),
INCLUDE_SUITE(sdl_tcp_socket),
INCLUDE_SUITE(SDL_MULTIPLAYER_WIN64),
INCLUDE_SUITE(SDL_MULTIPLAYER_UNIX),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_MULTIPLAYER, END_TESTS);

