#include <game_action/implemented/hitbox/MAIN_TEST_SUITE__CORE_GAME_ACTION_IMPLEMENTED_HITBOX.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED_HITBOX, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED_HITBOX, END_TESTS);

