#include <game_action/core/hitbox/MAIN_TEST_SUITE__CORE_GAME_ACTION_CORE_HITBOX.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_CORE_HITBOX, 2,
INCLUDE_SUITE(game_action__hitbox),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_CORE_HITBOX, END_TESTS);

