#include <world/implemented/MAIN_TEST_SUITE__CORE_WORLD_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_WORLD_IMPLEMENTED, 3,
INCLUDE_SUITE(tile_logic_table_registrar),
INCLUDE_SUITE(chunk_generator_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_WORLD_IMPLEMENTED, END_TESTS);

