#include <multiplayer/MAIN_TEST_SUITE__NO_GUI_MULTIPLAYER.h>

INCLUDE_SUB_SUITES(NO_GUI_MULTIPLAYER, 3,
INCLUDE_SUITE(no_gui_tcp_context),
INCLUDE_SUITE(no_gui_tcp_socket),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(NO_GUI_MULTIPLAYER, END_TESTS);

