#include <world/MAIN_TEST_SUITE__CORE_WORLD.h>

INCLUDE_SUB_SUITES(CORE_WORLD, 17,
INCLUDE_SUITE(camera),
INCLUDE_SUITE(region),
INCLUDE_SUITE(tile),
INCLUDE_SUITE(chunk_generator_table),
INCLUDE_SUITE(chunk),
INCLUDE_SUITE(world),
INCLUDE_SUITE(global_space),
INCLUDE_SUITE(chunk_pool),
INCLUDE_SUITE(local_space_manager),
INCLUDE_SUITE(local_space),
INCLUDE_SUITE(region_manager),
INCLUDE_SUITE(tile_logic_table),
INCLUDE_SUITE(global_space_manager),
INCLUDE_SUITE(CORE_WORLD_SERIALIZATION),
INCLUDE_SUITE(CORE_WORLD_IMPLEMENTED),
INCLUDE_SUITE(CORE_WORLD_PROCESS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_WORLD, END_TESTS);

