#include <game_action/core/MAIN_TEST_SUITE__CORE_GAME_ACTION_CORE.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_CORE, 7,
INCLUDE_SUITE(game_action__bad_request),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE_WORLD),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE_TCP),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE_ENTITY),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE_GLOBAL_SPACE),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE_HITBOX),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_CORE, END_TESTS);

