#include <world/serialization/MAIN_TEST_SUITE__CORE_WORLD_SERIALIZATION.h>

INCLUDE_SUB_SUITES(CORE_WORLD_SERIALIZATION, 2,
INCLUDE_SUITE(world_directory),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_WORLD_SERIALIZATION, END_TESTS);

