#include <scene/implemented/MAIN_TEST_SUITE__CORE_SCENE_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_SCENE_IMPLEMENTED, 3,
INCLUDE_SUITE(scene__main),
INCLUDE_SUITE(scene_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_SCENE_IMPLEMENTED, END_TESTS);

