#include <entity/MAIN_TEST_SUITE__CORE_ENTITY.h>

INCLUDE_SUB_SUITES(CORE_ENTITY, 3,
INCLUDE_SUITE(entity_manager),
INCLUDE_SUITE(entity),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_ENTITY, END_TESTS);

