#include <entity/MAIN_TEST_SUITE__CORE_ENTITY.h>

INCLUDE_SUB_SUITES(CORE_ENTITY, 4,
INCLUDE_SUITE(entity_manager),
INCLUDE_SUITE(entity),
INCLUDE_SUITE(CORE_ENTITY_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_ENTITY, END_TESTS);

