#include <game_action/MAIN_TEST_SUITE__CORE_GAME_ACTION.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION, 7,
INCLUDE_SUITE(game_action_logic_table),
INCLUDE_SUITE(game_action),
INCLUDE_SUITE(game_action_manager),
INCLUDE_SUITE(game_action_logic_entry),
INCLUDE_SUITE(CORE_GAME_ACTION_IMPLEMENTED),
INCLUDE_SUITE(CORE_GAME_ACTION_CORE),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION, END_TESTS);

