#include <serialization/win64/MAIN_TEST_SUITE__SDL_SERIALIZATION_WIN64.h>

INCLUDE_SUB_SUITES(SDL_SERIALIZATION_WIN64, 2,
INCLUDE_SUITE(win64_file_system),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_SERIALIZATION_WIN64, END_TESTS);

