#include "test_suite_game_action_core_global_space_game_action__global_space__request__offline.h"
#include "test_suite_game_action_core_global_space_game_action__global_space__request__multiplayer.h"
#include "test_suite_game_action_core_global_space_game_action__global_space__resolve.h"
#include "test_suite_game_action_core_global_space_game_action__global_space__store.h"

#include <test_util.h>

DECLARE_SUITE(CORE_GAME_ACTION_CORE_GLOBAL_SPACE);

