"""test_gen_tile_layer.py — Unit tests for tile layer registrar code generation.

Tests verify that _generate_registrar_c produces correct C type names
for single-layer and multi-layer configurations, ensuring non-first
layers do NOT get prefixed logical kind or record type names.
"""

import os
import tempfile
from unittest.mock import patch

import pytest

from lavender_tools.gen_tile_layer import (
    _create_tile_kind_h,
    _generate_registrar_c,
    LayerSpec,
)

# Minimal registrar .c template with empty GEN regions.
# _generate_registrar_c uses _set_region(last=True) for TABLES,
# so the SECOND GEN-TABLES pair (inside the function) is the one modified.
_REGISTRAR_TEMPLATE = """\
#include "world/implemented/tile_logic_table_registrar.h"
#include "world/tile_logic_context.h"
#include "defines_weak.h"
#include "types/implemented/world/tile_layer.h"

// GEN-INCLUDE-BEGIN
// GEN-INCLUDE-END

///
/// These comments are autogenerated and
/// modifying them will break automation.
///
// GEN-TABLES-BEGIN
// Tile_Layer__Default:
// GEN-TABLES-END

void register_tile_logic_tables(
        Game *p_game,
        Tile_Logic_Context *p_tile_logic_context) {
    // GEN-TABLES-BEGIN
    // GEN-TABLES-END
    
    // GEN-RECORDS-BEGIN
    // GEN-RECORDS-END
}
"""


@pytest.fixture
def captured_registrar_c():
    """Yield a dict that captures the content written by _generate_registrar_c.

    Patches:
      * _REGISTRAR_C -> temp file containing the template above
      * _write -> writes into the dict under key 'content' instead of disk
      * tool_history -> no-op mock (prevents side-effects from _write)
    """
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".c", delete=False
    ) as f:
        f.write(_REGISTRAR_TEMPLATE)
        temp_path = f.name

    captured = {}

    def fake_write(path, content):
        captured["path"] = path
        captured["content"] = content

    with patch("lavender_tools.gen_tile_layer._REGISTRAR_C", temp_path), \
         patch("lavender_tools.gen_tile_layer._write", side_effect=fake_write), \
         patch("lavender_tools.gen_tile_layer.tool_history"):
        yield captured

    os.unlink(temp_path)


@pytest.fixture
def captured_kind_h(tmp_path):
    """Capture content written by _create_tile_kind_h."""
    captured = {}

    def fake_write(path, content):
        captured["path"] = path
        captured["content"] = content

    with patch("lavender_tools.gen_tile_layer.PROJECT_ROOT", str(tmp_path)), \
         patch("lavender_tools.gen_tile_layer._write", side_effect=fake_write), \
         patch("lavender_tools.gen_tile_layer.tool_history"):
        yield captured


# ---------------------------------------------------------------------------
# Single-layer tests
# ---------------------------------------------------------------------------

def test_single_layer__uses_tile_kind_logical(captured_registrar_c):
    """Ground (first layer) should use Tile_Kind__Logical and Tile_Logic_Record."""
    spec = LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2)
    _generate_registrar_c([spec], ["Ground"])
    content = captured_registrar_c["content"]

    assert "Tile_Kind__Logical" in content
    assert "sizeof(Tile_Logic_Record)" not in content


# ---------------------------------------------------------------------------
# Multi-layer tests — type name uniformity
# ---------------------------------------------------------------------------

def test_multi_layer__no_prefixed_logical_names(captured_registrar_c):
    """Non-first layers must NOT get Tile_{Layer}_Kind__Logical names."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    assert "Tile_Structure_Kind__Logical" in content
    assert "Tile_Cover_Kind__Logical" in content


def test_multi_layer__no_prefixed_record_types(captured_registrar_c):
    """All layers must use plain Tile_Logic_Record (no __Layer suffix)."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    assert "Tile_Logic_Record__Ground" not in content
    assert "Tile_Logic_Record__Structure" not in content
    assert "Tile_Logic_Record__Cover" not in content
    assert "sizeof(Tile_Logic_Record)" not in content


# ---------------------------------------------------------------------------
# Multi-layer tests — GEN region contents
# ---------------------------------------------------------------------------

def test_multi_layer__gen_includes_all_layers(captured_registrar_c):
    """GEN-INCLUDE must contain tile_logic_context.h and all layer tables."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    include_start = content.find("// GEN-INCLUDE-BEGIN")
    include_end = content.find("// GEN-INCLUDE-END", include_start)
    include_region = content[include_start:include_end]

    assert '#include "world/tile_logic_context.h"' in include_region
    assert '#include "world/implemented/tile_logic_table__ground.h"' in include_region
    assert '#include "world/implemented/tile_logic_table__structure.h"' in include_region
    assert '#include "world/implemented/tile_logic_table__cover.h"' in include_region


def test_multi_layer__gen_records_all_layers(captured_registrar_c):
    """GEN-RECORDS must contain registration calls for every layer."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    records_start = content.find("// GEN-RECORDS-BEGIN")
    records_end = content.find("// GEN-RECORDS-END", records_start)
    records_region = content[records_start:records_end]

    assert "register_tile_logic_table__ground(" in records_region
    assert "register_tile_logic_table__structure(" in records_region
    assert "register_tile_logic_table__cover(" in records_region

    # Each call must reference the correct Tile_Layer enum value.
    assert "Tile_Layer__Ground" in records_region
    assert "Tile_Layer__Structure" in records_region
    assert "Tile_Layer__Cover" in records_region


# ---------------------------------------------------------------------------
# New regression tests for _generate_registrar_c bug fixes
# ---------------------------------------------------------------------------

def test_single_layer__correct_layer_enum(captured_registrar_c):
    """The generated allocation call must use Tile_Layer__Ground, not Tile_Layer__Default."""
    spec = LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2)
    _generate_registrar_c([spec], ["Ground"])
    content = captured_registrar_c["content"]

    # Find the LAST GEN-TABLES region (the one inside the function body)
    last_tables_begin = content.rfind("// GEN-TABLES-BEGIN")
    tables_end = content.find("// GEN-TABLES-END", last_tables_begin)
    tables_region = content[last_tables_begin:tables_end]

    assert "Tile_Layer__Ground" in tables_region
    assert "Tile_Layer__Default" not in tables_region


def test_multi_layer__each_layer_gets_own_enum(captured_registrar_c):
    """Every layer must receive its own Tile_Layer__* enum in the allocation calls."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    # Extract the LAST GEN-TABLES region (the one inside the function body)
    last_tables_begin = content.rfind("// GEN-TABLES-BEGIN")
    tables_end = content.find("// GEN-TABLES-END", last_tables_begin)
    tables_region = content[last_tables_begin:tables_end]

    assert "Tile_Layer__Ground" in tables_region
    assert "Tile_Layer__Structure" in tables_region
    assert "Tile_Layer__Cover" in tables_region
    assert "Tile_Layer__Default," not in tables_region


def test_multi_layer__two_arg_allocation_call(captured_registrar_c):
    """allocate_tile_logic_table__tile_logic_entries must be called with exactly 2 args."""
    specs = [
        LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Structure", total_bits=8, logic_bits=4, animation_bits=2),
        LayerSpec("Cover", total_bits=8, logic_bits=4, animation_bits=2),
    ]
    _generate_registrar_c(specs, ["Ground", "Structure", "Cover"])
    content = captured_registrar_c["content"]

    # Extract the LAST GEN-TABLES region (the one inside the function body)
    last_tables_begin = content.rfind("// GEN-TABLES-BEGIN")
    tables_end = content.find("// GEN-TABLES-END", last_tables_begin)
    tables_region = content[last_tables_begin:tables_end]

    assert "sizeof(" not in tables_region
    assert tables_region.count("allocate_tile_logic_table__tile_logic_entries(") == 3
    # First layer uses Tile_Kind__Logical, others use layer-specific names
    assert tables_region.count("Tile_Kind__Logical))") == 1
    assert tables_region.count("Tile_Structure_Kind__Logical))") == 1
    assert tables_region.count("Tile_Cover_Kind__Logical))") == 1


def test_single_layer__no_sizeof_in_tables(captured_registrar_c):
    """sizeof must not appear in the GEN-TABLES region for a single layer."""
    spec = LayerSpec("Ground", total_bits=8, logic_bits=4, animation_bits=2)
    _generate_registrar_c([spec], ["Ground"])
    content = captured_registrar_c["content"]

    # Extract the LAST GEN-TABLES region
    last_tables_begin = content.rfind("// GEN-TABLES-BEGIN")
    tables_end = content.find("// GEN-TABLES-END", last_tables_begin)
    tables_region = content[last_tables_begin:tables_end]

    assert "sizeof(" not in tables_region


# ---------------------------------------------------------------------------
# Tests for _create_tile_kind_h
# ---------------------------------------------------------------------------

def test_first_layer_kind_h__uses_tile_kind_prefix(captured_kind_h):
    """Ground (first layer) must use Tile_Kind__* sentinel names."""
    _create_tile_kind_h("Ground", is_first_layer=True)
    content = captured_kind_h["content"]

    assert "Tile_Kind__None" in content
    assert "Tile_Kind__Logical" in content
    assert "Tile_Kind__Unknown" in content


def test_non_first_layer_kind_h__uses_layer_specific_prefix(captured_kind_h):
    """Non-first layers must use Tile_{Layer}_Kind__* sentinel names."""
    _create_tile_kind_h("Cover", is_first_layer=False)
    content = captured_kind_h["content"]

    assert "Tile_Cover_Kind__None" in content
    assert "Tile_Cover_Kind__Logical" in content
    assert "Tile_Cover_Kind__Unknown" in content


def test_non_first_layer_kind_h__no_bare_tile_kind_prefix(captured_kind_h):
    """Non-first layers must NOT contain bare Tile_Kind__* names."""
    _create_tile_kind_h("Structure", is_first_layer=False)
    content = captured_kind_h["content"]

    assert "Tile_Kind__None" not in content
    assert "Tile_Kind__Logical" not in content
    assert "Tile_Kind__Unknown" not in content


def test_non_first_layer_kind_h__enum_tag_is_layer_specific(captured_kind_h):
    """Non-first layer enum typedef must use the layer-specific tag name."""
    _create_tile_kind_h("Cover", is_first_layer=False)
    content = captured_kind_h["content"]

    assert "typedef enum Tile_Cover_Kind" in content
    assert "} Tile_Cover_Kind;" in content


def test_non_first_layer_kind_h__logical_aliases_none(captured_kind_h):
    """Logical sentinel must alias None for non-first layers."""
    _create_tile_kind_h("Cover", is_first_layer=False)
    content = captured_kind_h["content"]

    assert "Tile_Cover_Kind__Logical = Tile_Cover_Kind__None" in content
