#include <input/MAIN_TEST_SUITE__SDL_INPUT.h>

INCLUDE_SUB_SUITES(SDL_INPUT, 3,
INCLUDE_SUITE(sdl_input),
INCLUDE_SUITE(SDL_INPUT_OPENGL),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SDL_INPUT, END_TESTS);

