#include <collisions/implemented/MAIN_TEST_SUITE__CORE_COLLISIONS_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_COLLISIONS_IMPLEMENTED, 2,
INCLUDE_SUITE(CORE_COLLISIONS_IMPLEMENTED_HITBOX_CONTEXT),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_COLLISIONS_IMPLEMENTED, END_TESTS);

