#include <entity/implemented/MAIN_TEST_SUITE__CORE_ENTITY_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_ENTITY_IMPLEMENTED, 2,
INCLUDE_SUITE(entity_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_ENTITY_IMPLEMENTED, END_TESTS);

