#include <ui/MAIN_TEST_SUITE__CORE_UI.h>

INCLUDE_SUB_SUITES(CORE_UI, 14,
INCLUDE_SUITE(ui_tile_span),
INCLUDE_SUITE(ui_button),
INCLUDE_SUITE(ui_tile_map),
INCLUDE_SUITE(ui_slider),
INCLUDE_SUITE(ui_tile_map_manager),
INCLUDE_SUITE(ui_context),
INCLUDE_SUITE(ui_draggable),
INCLUDE_SUITE(ui_drop_zone),
INCLUDE_SUITE(ui_tile),
INCLUDE_SUITE(ui_manager),
INCLUDE_SUITE(ui_element),
INCLUDE_SUITE(CORE_UI_IMPLEMENTED),
INCLUDE_SUITE(CORE_UI_HANDLERS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_UI, END_TESTS);

