#include <multiplayer/MAIN_TEST_SUITE__CORE_MULTIPLAYER.h>

INCLUDE_SUB_SUITES(CORE_MULTIPLAYER, 5,
INCLUDE_SUITE(client__default),
INCLUDE_SUITE(tcp_socket),
INCLUDE_SUITE(server__default),
INCLUDE_SUITE(tcp_socket_manager),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_MULTIPLAYER, END_TESTS);

