#include "world/implemented/tile_logic_table_registrar.h"
#include "defines_weak.h"
#include "types/implemented/world/tile_layer.h"

///
/// These comments are autogenerated and
/// modifying them will break automation.
///
// GEN-TABLES-BEGIN
// Tile_Layer__Default:
// GEN-TABLES-END

void register_tile_logic_tables(
        Game *p_game,
        Tile_Logic_Context *p_tile_logic_context) {
    // GEN-TABLES-BEGIN
    // GEN-TABLES-END
    
    // GEN-RECORDS-BEGIN
    // GEN-RECORDS-END
}

