#include <game_action/implemented/MAIN_TEST_SUITE__CORE_GAME_ACTION_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED, 2,
INCLUDE_SUITE(game_action__registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_IMPLEMENTED, END_TESTS);

