#!/bin/sh

print_usage() {
    printf \
    "Usage: run_ui_builder.sh <-b BACKEND> [-f UI_FILE_NAME]
        run_ui_builder.sh will use tools/ui_builder.py to generate .c and .h
        files based on the [-f UI_FILE_NAME].xml configuration.

            -b\ttarget backend
            -f\tspecific ui file to generate from
            -d\tflags to pass into ./tools/ui_builder.py\n"
}

BACKEND='NDS'
FILE_SEARCH='*'
ARGS=""

while getopts 'b:f:d:c' flag; do
    case "$flag" in
        f) FILE_SEARCH="$OPTARG" ;;
        b) BACKEND="$OPTARG" ;;
        d) ARGS="$OPTARG" ;;
        \?) ;;
        *) print_usage
            exit 1 ;;
    esac
done

if [ "$FILE_SEARCH" = "*" ]; then
    print_usage
    printf "\n\tREQUIRED: -f\n"
    exit 1
fi

if [ "$(echo $FILE_SEARCH | sed 's/[^\*]//g' | sed 's/(\*)*/\*/')" = "*" ]; then
    print_usage
    printf "\n\tERROR: cannot use wild characters in -f\n"
    exit 1
fi

BASENAME=$(basename $FILE_SEARCH)

BACKEND=$(echo $BACKEND | tr '[:upper:]' '[:lower:]')
FULLPATH="./assets/ui/xml/$BACKEND/${FILE_SEARCH#*"$BACKEND"/}"

XML=$(find ./assets/ui/xml/$BACKEND -iname $BASENAME)

if [ -z "$XML" ]; then
    if [ ! -f "$FULLPATH" ]; then
        cp $LAVENDER_DIR/tools/_ui_sample.xml $FULLPATH
        UPPER_BACKEND=$(echo $BACKEND | tr '[:lower:]' '[:upper:]')
        sed -i "s/_REPLACE_FILE_NAME/${BASENAME%.*}/g" $FULLPATH
        sed -i "s/_REPLACE_BACKEND/$UPPER_BACKEND/g" $FULLPATH
    else
        XML=$FULLPATH
    fi
fi

python $LAVENDER_DIR/tools/ui_builder.py $XML $ARGS &
VISUALIZER_PID=$!
if [ -z "$(echo $ARGS | grep "is_visualizing false")" ]; then
    nvim $XML &
    NVIM_PID=$!
    wait $NVIM_PID
    kill $VISUALIZER_PID
else
    wait $VISUALIZER_PID
fi
