#!/usr/bin/env python3
"""
gen_png.py - Generate sprite sheet PNG(s) with distinctive per-frame colors.

Usage:
    python gen_png.py \
        --output <path relative to ./assets> \
        --frame-resolution <8|16|32|64|128|256|512|1024> \
        --row-count <int> \
        --column-count <int> \
        [--groups [path_to_json]]

If --groups is given without a value, reads JSON from stdin until EOF.
"""

import argparse
import json
import os
import sys
from abc import ABC, abstractmethod

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow",
          file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Color format system (extensible)
# ---------------------------------------------------------------------------

class ColorFormat(ABC):
    """
    Base class for color formats.
    Each implementation must provide 1024 unique colors and 1 unused color.
    Colors are returned as (R, G, B, A) tuples with values 0-255.
    """

    @abstractmethod
    def unused_color(self):
        """Return the single unused / background color as (R,G,B,A)."""
        ...

    @abstractmethod
    def unique_color(self, index):
        """
        Return a unique color for *index* (0 .. 1023).
        Must not collide with unused_color().
        """
        ...

    @abstractmethod
    def parse_color_string(self, color_string):
        """Parse a color string (e.g. '255,255,255,255') into (R,G,B,A)."""
        ...


class ARGBColorFormat(ColorFormat):
    """
    ARGB colour format.
    * Unused color: fully-transparent magenta (255, 0, 255, 0)
    * 1024 unique colors are generated by distributing across the RGB cube
      while keeping A=255 and avoiding the unused color.
    """

    def unused_color(self):
        return (255, 0, 255, 0)  # stored as RGBA for Pillow

    def unique_color(self, index):
        """
        Generate 1024 unique opaque colours.
        We use a 10-bit index split into R(4), G(3), B(3) giving
        16*8*8 = 1024 colours.  Values are spread across 0-255.
        If a generated colour matches the unused colour we nudge it.
        """
        if index < 0 or index > 1023:
            raise ValueError(f"Color index out of range: {index}")

        r_bits = (index >> 6) & 0xF   # 4 bits -> 0..15
        g_bits = (index >> 3) & 0x7   # 3 bits -> 0..7
        b_bits = index & 0x7          # 3 bits -> 0..7

        r = int(r_bits * 255 / 15)
        g = int(g_bits * 255 / 7)
        b = int(b_bits * 255 / 7)
        a = 255

        # Avoid collision with unused colour (R=255,G=0,B=255,A=0)
        # Since a==255 and unused has a==0 they already differ, but
        # guard against the RGB part matching anyway for visual clarity.
        if (r, g, b) == (255, 0, 255):
            b = 254

        return (r, g, b, a)

    def parse_color_string(self, color_string):
        """Parse 'A,R,G,B' string into (R,G,B,A) for Pillow."""
        parts = [int(p.strip()) for p in color_string.split(",")]
        if len(parts) != 4:
            raise ValueError(
                f"ARGB color must have 4 components, got {len(parts)}: "
                f"'{color_string}'")
        a, r, g, b = parts
        for name, val in [("A", a), ("R", r), ("G", g), ("B", b)]:
            if val < 0 or val > 255:
                raise ValueError(
                    f"ARGB component {name} out of range: {val}")
        return (r, g, b, a)


COLOR_FORMATS = {
    "ARGB": ARGBColorFormat,
}


# ---------------------------------------------------------------------------
# Schema / argument validation helpers
# ---------------------------------------------------------------------------

VALID_RESOLUTIONS = {2**n for n in range(3, 11)}  # 8..1024


def validate_positive_nonzero_int(value, name):
    if not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive non-zero integer, "
                         f"got: {value}")


def validate_groups_schema(groups_obj, max_rows, max_cols):
    """Validate the groups JSON object against the specification."""
    if not isinstance(groups_obj, dict):
        raise ValueError("Groups JSON must be an object (dict).")

    orientation = groups_obj.get("orientation")
    if orientation not in ("column", "row"):
        raise ValueError(
            f"'orientation' must be 'column' or 'row', got: {orientation}")

    groups = groups_obj.get("groups")
    if not isinstance(groups, list):
        raise ValueError("'groups' must be a list.")

    for i, grp in enumerate(groups):
        for field in ("row-begin", "column-begin", "row-end", "column-end",
                       "format", "color"):
            if field not in grp:
                raise ValueError(
                    f"Group {i}: missing required field '{field}'.")

        rb = grp["row-begin"]
        cb = grp["column-begin"]
        re = grp["row-end"]
        ce = grp["column-end"]

        for name, val in [("row-begin", rb), ("column-begin", cb),
                          ("row-end", re), ("column-end", ce)]:
            validate_positive_nonzero_int(val, f"Group {i} '{name}'")

        if rb >= re:
            raise ValueError(
                f"Group {i}: row-begin ({rb}) must be < row-end ({re}).")
        if cb >= ce:
            raise ValueError(
                f"Group {i}: column-begin ({cb}) must be < "
                f"column-end ({ce}).")
        if re > max_rows:
            raise ValueError(
                f"Group {i}: row-end ({re}) exceeds row-count ({max_rows}).")
        if ce > max_cols:
            raise ValueError(
                f"Group {i}: column-end ({ce}) exceeds "
                f"column-count ({max_cols}).")

        fmt = grp["format"]
        if fmt not in COLOR_FORMATS:
            raise ValueError(
                f"Group {i}: unsupported format '{fmt}'. "
                f"Supported: {list(COLOR_FORMATS.keys())}")

    return groups_obj


# ---------------------------------------------------------------------------
# Image generation
# ---------------------------------------------------------------------------

def fill_rect(img, x, y, w, h, color):
    """Fill a rectangle in *img* with *color* (R,G,B,A)."""
    for py in range(y, y + h):
        for px in range(x, x + w):
            img.putpixel((px, py), color)


def generate_images(output_path, frame_res, row_count, col_count,
                    groups_obj):
    """
    Core generation logic.

    * Total pixel area = row_count * col_count * frame_res^2
    * If < 1024*1024  -> single PNG (clamped to actual size).
    * If >= 1024*1024 -> one PNG per frame in a folder.
    """
    total_pixels = row_count * col_count * (frame_res ** 2)
    single_file = total_pixels < 1024 * 1024

    # Default colour format for non-grouped frames
    default_cf = ARGBColorFormat()
    unused = default_cf.unused_color()

    # Pre-compute per-frame colours (for non-grouped frames)
    total_frames = row_count * col_count

    # Build a set of frames that belong to a group so we can skip them
    # when assigning individual colours.
    grouped_frames = {}  # (row_idx, col_idx) -> group index
    group_colors = {}    # group index -> (R,G,B,A)

    if groups_obj is not None:
        for gi, grp in enumerate(groups_obj["groups"]):
            fmt_cls = COLOR_FORMATS[grp["format"]]
            cf = fmt_cls()
            color = cf.parse_color_string(grp["color"])
            group_colors[gi] = color
            for r in range(grp["row-begin"] - 1, grp["row-end"]):
                for c in range(grp["column-begin"] - 1, grp["column-end"]):
                    grouped_frames[(r, c)] = gi

    # Assign unique colours to non-grouped frames
    color_index = 0
    frame_colors = {}  # (row, col) -> (R,G,B,A)
    for r in range(row_count):
        for c in range(col_count):
            if (r, c) in grouped_frames:
                frame_colors[(r, c)] = group_colors[grouped_frames[(r, c)]]
            else:
                frame_colors[(r, c)] = default_cf.unique_color(
                    color_index % 1024)
                color_index += 1

    if single_file:
        img_w = col_count * frame_res
        img_h = row_count * frame_res
        img = Image.new("RGBA", (img_w, img_h), unused)

        for r in range(row_count):
            for c in range(col_count):
                fx = c * frame_res
                fy = r * frame_res
                color = frame_colors[(r, c)]

                if (r, c) in grouped_frames:
                    # Fill frame body (skip first row & first column for
                    # border).
                    # First row of frame -> unused (border)
                    # First column of frame -> unused (border)
                    # The unused colour is already the background so we
                    # only need to fill the interior.
                    fill_rect(img,
                              fx + 1, fy + 1,
                              frame_res - 1, frame_res - 1,
                              color)
                else:
                    fill_rect(img, fx, fy, frame_res, frame_res, color)

        abs_output = os.path.join("./assets", output_path)
        os.makedirs(os.path.dirname(abs_output) or ".", exist_ok=True)
        img.save(abs_output)
        print(f"Wrote single file: {abs_output}  ({img_w}x{img_h})")

    else:
        # Multi-file mode: one PNG per frame, output path is a folder.
        abs_folder = os.path.join("./assets", output_path)
        os.makedirs(abs_folder, exist_ok=True)

        base_name = os.path.basename(output_path.rstrip("/"))
        frame_idx = 0
        for r in range(row_count):
            for c in range(col_count):
                img = Image.new("RGBA", (frame_res, frame_res), unused)
                color = frame_colors[(r, c)]

                if (r, c) in grouped_frames:
                    fill_rect(img, 1, 1,
                              frame_res - 1, frame_res - 1, color)
                else:
                    fill_rect(img, 0, 0, frame_res, frame_res, color)

                fname = f"{base_name}_{frame_idx}.png"
                fpath = os.path.join(abs_folder, fname)
                img.save(fpath)
                frame_idx += 1

        print(f"Wrote {frame_idx} files to: {abs_folder}/")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

class StoreOptionalPath(argparse.Action):
    """
    Custom action for --groups:
      * not supplied  -> dest = None
      * --groups      -> dest = "" (read from stdin)
      * --groups path -> dest = "path"
    """
    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, values if values is not None else "")


def build_parser():
    parser = argparse.ArgumentParser(
        description="Generate sprite-sheet PNG(s) with distinctive frame "
                    "colours.")
    parser.add_argument(
        "--output", required=True,
        help="Output file path relative to ./assets (include filename or "
             "folder name).")
    parser.add_argument(
        "--frame-resolution", required=True, type=int,
        help="Frame size in pixels (power of 2, 8-1024).")
    parser.add_argument(
        "--row-count", required=True, type=int,
        help="Number of rows (positive non-zero integer).")
    parser.add_argument(
        "--column-count", required=True, type=int,
        help="Number of columns (positive non-zero integer).")
    parser.add_argument(
        "--groups", nargs="?", default=None, action=StoreOptionalPath,
        help="Optional. Path to groups JSON file, or omit value to read "
             "from stdin.")
    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    # --- Validate frame-resolution ---
    if args.frame_resolution not in VALID_RESOLUTIONS:
        parser.error(
            f"--frame-resolution must be a power of 2 between 8 and 1024, "
            f"got: {args.frame_resolution}")

    # --- Validate row-count / column-count ---
    if args.row_count <= 0:
        parser.error("--row-count must be a positive non-zero integer.")
    if args.column_count <= 0:
        parser.error("--column-count must be a positive non-zero integer.")

    # --- Handle --groups ---
    groups_obj = None
    if args.groups is not None:
        if args.groups == "":
            # Read from stdin
            raw = sys.stdin.read()
        else:
            gpath = args.groups
            if not os.path.isfile(gpath):
                parser.error(f"Groups file not found: {gpath}")
            with open(gpath, "r") as f:
                raw = f.read()

        try:
            groups_obj = json.loads(raw)
        except json.JSONDecodeError as e:
            parser.error(f"Invalid JSON for --groups: {e}")

        try:
            validate_groups_schema(groups_obj, args.row_count,
                                   args.column_count)
        except ValueError as e:
            parser.error(str(e))

    # --- Generate ---
    generate_images(
        output_path=args.output,
        frame_res=args.frame_resolution,
        row_count=args.row_count,
        col_count=args.column_count,
        groups_obj=groups_obj,
    )


if __name__ == "__main__":
    main()
