#include <MAIN_TEST_SUITE__CORE_ANCIENTS_GAME.h>

INCLUDE_SUB_SUITES(CORE_ANCIENTS_GAME, 26,
INCLUDE_SUITE(main),
INCLUDE_SUITE(vectors),
INCLUDE_SUITE(core_string),
INCLUDE_SUITE(random),
INCLUDE_SUITE(client),
INCLUDE_SUITE(degree),
INCLUDE_SUITE(game),
INCLUDE_SUITE(CORE_INPUT),
INCLUDE_SUITE(CORE_RENDERING),
INCLUDE_SUITE(CORE_WORLD),
INCLUDE_SUITE(CORE_INVENTORY),
INCLUDE_SUITE(CORE_SORT),
INCLUDE_SUITE(CORE_DEBUG),
INCLUDE_SUITE(CORE_AUDIO),
INCLUDE_SUITE(CORE_LOG),
INCLUDE_SUITE(CORE_SERIALIZATION),
INCLUDE_SUITE(CORE_GAME_ACTION),
INCLUDE_SUITE(CORE_ENTITY),
INCLUDE_SUITE(CORE_UI),
INCLUDE_SUITE(CORE_COLLISIONS),
INCLUDE_SUITE(CORE_UTIL),
INCLUDE_SUITE(CORE_MULTIPLAYER),
INCLUDE_SUITE(CORE_RAYCAST),
INCLUDE_SUITE(CORE_PROCESS),
INCLUDE_SUITE(CORE_SCENE),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_ANCIENTS_GAME, END_TESTS);

