#include <game_action/core/input/MAIN_TEST_SUITE__CORE_GAME_ACTION_CORE_INPUT.h>

INCLUDE_SUB_SUITES(CORE_GAME_ACTION_CORE_INPUT, 2,
INCLUDE_SUITE(game_action__input),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_GAME_ACTION_CORE_INPUT, END_TESTS);

