#include <collisions/core/MAIN_TEST_SUITE__CORE_COLLISIONS_CORE.h>

INCLUDE_SUB_SUITES(CORE_COLLISIONS_CORE, 2,
INCLUDE_SUITE(CORE_COLLISIONS_CORE_AABB),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_COLLISIONS_CORE, END_TESTS);

