#include <scene/MAIN_TEST_SUITE__CORE_SCENE.h>

INCLUDE_SUB_SUITES(CORE_SCENE, 4,
INCLUDE_SUITE(scene),
INCLUDE_SUITE(scene_manager),
INCLUDE_SUITE(CORE_SCENE_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_SCENE, END_TESTS);

