#include <MAIN_TEST_SUITE__NO_GUI_ANCIENTS_GAME.h>

INCLUDE_SUB_SUITES(NO_GUI_ANCIENTS_GAME, 8,
INCLUDE_SUITE(no_gui_game),
INCLUDE_SUITE(no_gui_main),
INCLUDE_SUITE(NOT_IMPL),
INCLUDE_SUITE(NO_GUI_DEBUG),
INCLUDE_SUITE(NO_GUI_SERIALIZATION),
INCLUDE_SUITE(NO_GUI_TIME),
INCLUDE_SUITE(NO_GUI_MULTIPLAYER),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(NO_GUI_ANCIENTS_GAME, END_TESTS);

