#include <sort/MAIN_TEST_SUITE__CORE_SORT.h>

INCLUDE_SUB_SUITES(CORE_SORT, 3,
INCLUDE_SUITE(heap_sort__opaque),
INCLUDE_SUITE(CORE_SORT_SORT_LIST),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(CORE_SORT, END_TESTS);

